### ISSUE TITLE
error during make command:

### ISSUE THREAD

**Issue by kalice123** [jwestfall69/neogeo-diag-bios#17]
error during make command:
vasmm68k_mot -Fbin -m68000 -spaces -L debug/sp1.asm.txt -chklabels -o output/sp1.raw sp1.asm
make: vasmm68k_mot: Command not found
Makefile:9: recipe for target 'output/sp1.bin' failed
make: *** [output/sp1.bin] Error 127

vasmm68k_mot is present in the directory.

**Comment by kalice123** [comment]
I solved adding PATH

**Comment by jwestfall69** [comment]
Glad you got it working.  Let me know if you have any other issues.
