### ISSUE TITLE
building the memory card branch gives some errors

### ISSUE THREAD

**Issue by alexcom84** [jwestfall69/neogeo-diag-bios#21]
![sp1 memorycard](https://user-images.githubusercontent.com/32986061/103343639-d5eeb580-4a8c-11eb-8f47-4db70106d579.PNG)

**Comment by jwestfall69** [comment]
I will fix this up this afternoon, must be a new restriction in vasm 1.8i.  I've been building with 1.8h.

**Comment by alexcom84** [comment]
Oh thanks, good to know. Used an old copy of 1.8f and managed to build it. 
I'll test this memcard branch on AES and some MV2F.

**Comment by jwestfall69** [comment]
Thanks, let me know if you find any other issues.  I've been testing on 2/4/6 boards and with a bunch of different memory cards.  I have them setup to I can trigger specific faults.
