### ISSUE TITLE
VRAM 2K DEAD OUTPUT (UPPER)

### ISSUE THREAD

**Issue by Icelvlan88** [jwestfall69/neogeo-diag-bios#22]
Hello,

Do you know what this error means? Cannot find anything outside on it.

VRAM 2K DEAD OUTPUT (UPPER)

**Comment by Rolel** [comment]
It means the RAM seems to be outputting nothing when attempting to read it. Most commons causes are  dead RAM (very likely for 2k RAM) or the RAM /OE trace may be cut.

**Comment by Icelvlan88** [comment]
I swapped them and check pin 20. Was hoping there might be another reason. I’m not getting any sprites just text.

**Comment by Icelvlan88** [comment]
Hmm my OE is grounded. Where is supposed to go back to?

**Comment by Icelvlan88** [comment]
These are CXK581P-35L

**Comment by Icelvlan88** [comment]
Fixed problem.
